steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - gcloud secrets versions access latest --secret=github-ssh --format='get(payload.data)'
        | tr '_-' '/+' | base64 -d > /root/.ssh/id_rsa
    id: git secret
    volumes:
      - name: ssh
        path: /root/.ssh
  - name: gcr.io/cloud-builders/git
    entrypoint: bash
    args:
      - -c
      - |-
        chmod 600 /root/.ssh/id_rsa
        cat <<EOF >known_hosts
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
        EOF
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_rsa
        EOF
        mv known_hosts /root/.ssh/known_hosts
        git config --global user.name "googleCloudRunner"
        git config --global user.email "cr_buildstep_gitsetup@googleCloudRunner.com"
    id: git setup script
    volumes:
      - name: ssh
        path: /root/.ssh
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - ${_PUSH_NAME}
      - repo
    id: clone to repo dir
    volumes:
      - name: ssh
        path: /root/.ssh
  - name: gcr.io/gcer-public/targets
    args:
      - Rscript
      - -e
      - renv::restore()
    id: Restore packages
    dir: repo
  - name: gcr.io/gcer-public/targets
    args:
      - Rscript
      - -e
      - targets::tar_make()
    id: target pipeline
    dir: repo
  - name: gcr.io/cloud-builders/git
    args:
      - add
      - --all
    dir: repo
    volumes:
      - name: ssh
        path: /root/.ssh
  - name: gcr.io/cloud-builders/git
    args:
      - commit
      - -a
      - -m
      - 'Add target run from ${COMMIT_SHA}: $(date +"%Y%m%dT%H:%M:%S")'
    dir: repo
    volumes:
      - name: ssh
        path: /root/.ssh
  - name: gcr.io/cloud-builders/git
    args:
      - push
    dir: repo
    volumes:
      - name: ssh
        path: /root/.ssh
substitutions:
  _PUSH_NAME: $(push.repository.name)
#Generated by googleCloudRunner::cr_build_write at 2021-12-10 22:14:18
